name: 2 - Docker Build and Push

on:
  workflow_dispatch:  # Manual trigger

env:
  ENVIRONMENT: 'dev'

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    environment: dev
    
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug File Structure
      run: |
        echo "=== Current Directory ==="
        pwd
        echo "=== Patient Service Files ==="
        ls -la apps/patient-service/
        echo "=== Appointment Service Files ==="
        ls -la apps/appointment-service/
        echo "=== File Contents ==="
        cat apps/patient-service/Dockerfile
        cat apps/appointment-service/Dockerfile

    - name: Login to Azure CLI with Service Principal
      run: |
        az login --service-principal \
          -u ${{ secrets.ARM_CLIENT_ID }} \
          -p ${{ secrets.ARM_CLIENT_SECRET }} \
          --tenant ${{ secrets.ARM_TENANT_ID }}
        
        az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Get ACR Credentials
      id: acr-creds
      run: |
        ACR_NAME="acrdev7459df5c"
        RESOURCE_GROUP="rg-dev-ab993d7f"
        
        echo "Getting ACR credentials for: $ACR_NAME in resource group: $RESOURCE_GROUP"
        
        # Enable admin user
        az acr update -n $ACR_NAME --resource-group $RESOURCE_GROUP --admin-enabled true
        
        # Get credentials
        ACR_USERNAME=$(az acr credential show --name $ACR_NAME --resource-group $RESOURCE_GROUP --query "username" -o tsv)
        ACR_PASSWORD=$(az acr credential show --name $ACR_NAME --resource-group $RESOURCE_GROUP --query "passwords[0].value" -o tsv)
        ACR_LOGIN_SERVER=$(az acr show --name $ACR_NAME --resource-group $RESOURCE_GROUP --query "loginServer" -o tsv)
        
        # Set outputs
        echo "username=$ACR_USERNAME" >> $GITHUB_OUTPUT
        echo "password=$ACR_PASSWORD" >> $GITHUB_OUTPUT
        echo "login-server=$ACR_LOGIN_SERVER" >> $GITHUB_OUTPUT
        
        echo "ACR Registry: $ACR_LOGIN_SERVER"

    - name: Log in to Azure Container Registry
      run: |
        echo "${{ steps.acr-creds.outputs.password }}" | docker login ${{ steps.acr-creds.outputs.login-server }} -u ${{ steps.acr-creds.outputs.username }} --password-stdin

    - name: Build and Push Patient Service (Simple Docker)
      run: |
        echo "Building Patient Service with regular Docker..."
        cd apps/patient-service
        
        # Build with regular docker command
        docker build -t ${{ steps.acr-creds.outputs.login-server }}/patient-service:latest .
        
        # Push the image
        docker push ${{ steps.acr-creds.outputs.login-server }}/patient-service:latest
        
        echo "✅ Patient Service image pushed successfully"

    - name: Build and Push Appointment Service (Simple Docker)
      run: |
        echo "Building Appointment Service with regular Docker..."
        cd apps/appointment-service
        
        # Build with regular docker command
        docker build -t ${{ steps.acr-creds.outputs.login-server }}/appointment-service:latest .
        
        # Push the image
        docker push ${{ steps.acr-creds.outputs.login-server }}/appointment-service:latest
        
        echo "✅ Appointment Service image pushed successfully"

    - name: Verify Images in ACR
      run: |
        echo "Verifying images were pushed to ACR..."
        az acr repository list --name acrdev7459df5c --output table

    - name: Run Trivy vulnerability scanner
      run: |
        echo "Running security scan on pushed images..."
        # Pull images first for scanning
        docker pull ${{ steps.acr-creds.outputs.login-server }}/patient-service:latest
        docker pull ${{ steps.acr-creds.outputs.login-server }}/appointment-service:latest
        
        trivy image \
          --format sarif \
          --output trivy-results.sarif \
          ${{ steps.acr-creds.outputs.login-server }}/patient-service:latest \
          ${{ steps.acr-creds.outputs.login-server }}/appointment-service:latest

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Create Build Summary
      run: |
        echo "Docker images built and pushed at $(date)" > docker-build-summary.txt
        echo "Patient Service: ${{ steps.acr-creds.outputs.login-server }}/patient-service:latest" >> docker-build-summary.txt
        echo "Appointment Service: ${{ steps.acr-creds.outputs.login-server }}/appointment-service:latest" >> docker-build-summary.txt
        echo "ACR Registry: ${{ steps.acr-creds.outputs.login-server }}" >> docker-build-summary.txt

    - name: Upload Build Summary
      uses: actions/upload-artifact@v4
      with:
        name: docker-build-summary
        path: docker-build-summary.txt
        retention-days: 30

    - name: Docker Build Complete
      run: |
        echo "✅ Docker build and push completed successfully!"
        echo "Images available in ACR:"
        echo "- ${{ steps.acr-creds.outputs.login-server }}/patient-service:latest"
        echo "- ${{ steps.acr-creds.outputs.login-server }}/appointment-service:latest"