name: 1 - Terraform Infrastructure

on:
  workflow_dispatch:  # Manual trigger...
  push:
    branches: [ main ]
    
env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ENVIRONMENT: 'dev'
  TF_WORKING_DIR: 'infrastructure/environments/dev'

jobs:
  terraform:
    name: 'Terraform - Provision Infrastructure'
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.6.0'

    - name: Terraform Format
      id: fmt
      run: |
        terraform -chdir=${{ env.TF_WORKING_DIR }} fmt -check -recursive
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

    - name: Terraform Validate
      id: validate
      run: terraform -chdir=${{ env.TF_WORKING_DIR }} validate

    - name: Terraform Plan
      id: plan
      run: |
        terraform -chdir=${{ env.TF_WORKING_DIR }} plan \
          -var="environment=${{ env.ENVIRONMENT }}" \
          -input=false \
          -out=tfplan

    - name: Terraform Apply - Phase 1 (Resource Group)
      id: apply-phase1
      if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
      run: |
        terraform -chdir=${{ env.TF_WORKING_DIR }} apply -auto-approve -target=module.resource_group

    - name: Wait for Resource Group Propagation
      if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
      run: |
        echo "Waiting 15 seconds for resource group to be fully propagated..."
        sleep 15

    - name: Terraform Apply - Phase 2 (Network, Storage, ACR)
      id: apply-phase2
      if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
      run: |
        terraform -chdir=${{ env.TF_WORKING_DIR }} apply -auto-approve \
          -target=module.network \
          -target=module.storage \
          -target=module.acr

    - name: Wait for Network Resources
      if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
      run: |
        echo "Waiting 30 seconds for network resources to be fully provisioned..."
        sleep 30

    - name: Terraform Apply - Phase 3 (AKS)
      id: apply-phase3
      if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
      run: |
        terraform -chdir=${{ env.TF_WORKING_DIR }} apply -auto-approve -target=module.aks

    - name: Get AKS Outputs
      id: outputs
      # Only run if ALL apply phases were successful AND we're on main branch or manual trigger
      if: |
        steps.apply-phase1.outcome == 'success' &&
        steps.apply-phase2.outcome == 'success' && 
        steps.apply-phase3.outcome == 'success' &&
        (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch')
      run: |
        cd ${{ env.TF_WORKING_DIR }}
        
        # Remove error suppression to fail properly if outputs aren't available
        AKS_CLUSTER_NAME=$(terraform output -raw cluster_name)
        AKS_RESOURCE_GROUP=$(terraform output -raw resource_group_name)
        ACR_NAME=$(terraform output -raw acr_name)
        
        echo "AKS_CLUSTER_NAME=$AKS_CLUSTER_NAME" >> $GITHUB_ENV
        echo "AKS_RESOURCE_GROUP=$AKS_RESOURCE_GROUP" >> $GITHUB_ENV
        echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV
        
        echo "AKS Cluster: $AKS_CLUSTER_NAME"
        echo "Resource Group: $AKS_RESOURCE_GROUP"
        echo "ACR Name: $ACR_NAME"

    - name: Update GitHub Environment
      # Only run if outputs step was successful (indicating all infrastructure was deployed)
      if: steps.outputs.outcome == 'success'
      run: |
        echo "Infrastructure deployment completed successfully!"
        echo "AKS Cluster: ${{ env.AKS_CLUSTER_NAME }}"
        echo "Resource Group: ${{ env.AKS_RESOURCE_GROUP }}"
        echo "ACR: ${{ env.ACR_NAME }}"

    - name: Create Deployment Tag
      # Only run if outputs step was successful
      if: steps.outputs.outcome == 'success'
      run: |
        echo "Infrastructure deployed at $(date)" > infrastructure-deployment.txt
        echo "AKS Cluster: ${{ env.AKS_CLUSTER_NAME }}" >> infrastructure-deployment.txt
        echo "Resource Group: ${{ env.AKS_RESOURCE_GROUP }}" >> infrastructure-deployment.txt
        echo "ACR: ${{ env.ACR_NAME }}" >> infrastructure-deployment.txt

    - name: Upload Infrastructure Details
      # Only run if outputs step was successful
      if: steps.outputs.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: infrastructure-details
        path: infrastructure-deployment.txt
        retention-days: 30

    # Add a failure notification step
    - name: Notify on Failure
      if: |
        failure() && 
        (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch')
      run: |
        echo "## Terraform Deployment Failed" >> $GITHUB_STEP_SUMMARY
        echo "One or more Terraform apply phases failed. Check the logs above for details." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Failed phases:" >> $GITHUB_STEP_SUMMARY
        echo "- Phase 1 (Resource Group): ${{ steps.apply-phase1.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "- Phase 2 (Network, Storage, ACR): ${{ steps.apply-phase2.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "- Phase 3 (AKS): ${{ steps.apply-phase3.outcome }}" >> $GITHUB_STEP_SUMMARY